package ev_cizimi;


import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import javax.swing.JFrame;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author user
 */
public class burakEv extends javax.swing.JPanel {

    /**
     * Creates new form chatgpt
     */
    public burakEv() {
        initComponents();
        setDoubleBuffered(true);
    }
     public void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D grafikler = (Graphics2D) g;
        grafikler.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

        grafikler.setColor(Color.BLACK);
        temelCiz(grafikler, 100, 200, 300, 250, Color.DARK_GRAY);
        catiCiz(grafikler, 100, 200, 300, 130, Color.RED); 
        kapiCiz(grafikler, 215, 290, 70, 140, Color.ORANGE);
        pencereCiz(grafikler, 120, 230, 60, 67, Color.CYAN); 
        pencereCiz(grafikler, 320, 230, 60, 70, Color.CYAN);  
        bacaCiz(grafikler, 120, 120, 20, 70,  Color.DARK_GRAY);
    }
      public void temelCiz(Graphics2D grafikler, int x, int y, int width, int height, Color cizgiRengi) {
        grafikler.setColor(cizgiRengi);
        grafikler.fillRect(x, y, width, height);
    }

    public void catiCiz(Graphics2D grafikler, int x,int y, int width, int height, Color cizgiRengi) {
        grafikler.setColor(cizgiRengi);
        int[] xPoints = {x, x + width / 2, x + width};
        int [] yPoints ={y, y - height, y};
        grafikler.fillPolygon(xPoints, yPoints, 3);
    }

    public void kapiCiz(Graphics2D grafikler, int x, int y, int width, int height, Color cizgiRengi) {
        grafikler.setColor(cizgiRengi);
        grafikler.fillRect(x, y, width, height);
        int kapiKoluX = x + width - 10;  
        int kapiKoluY = y + height / 2 - 5;  
        int kapiKoluBoyut = 7;  
        grafikler.setColor(Color.BLACK); 
        grafikler.fillOval(kapiKoluX, kapiKoluY, kapiKoluBoyut, kapiKoluBoyut);  
    }

    public void pencereCiz(Graphics2D grafikler, int x, int y, int width, int height, Color cizgiRengi) {
        grafikler.setColor(cizgiRengi);
        grafikler.fillRect(x, y, width, height);
     

        grafikler.setColor(Color.BLACK);  
        grafikler.setStroke(new BasicStroke(2));  
        grafikler.fillRect(x, y + height / 2 - 2, width, 2); 
        grafikler.fillRect(x, y + height / 2 - 2, width, 2);  
        grafikler.fillRect(x + width / 2 - 2, y, 2, height);  
        grafikler.fillRect(x + width / 2 - 2, y, 2, height);      
        }

        public void bacaCiz(Graphics2D grafikler, int x, int y, int width, int height, Color cizgiRengi) {
        grafikler.setColor(cizgiRengi);
        grafikler.fillRect(x, y, width, height);
        
        }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 488, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 366, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

       public static void main(String[] args) {
        JFrame pencere = new JFrame("Evim Evim Güzel Evim");
        burakEv g2DPanel = new burakEv();
        pencere.setSize(500, 500);
        pencere.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        pencere.add(g2DPanel);
        pencere.setVisible(true);
    }
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

